### PR TITLE
update machina version, deprecated machina syntax

### PR DESCRIPTION
**Pull request by aprilb**
- New Machina version.
- Updated syntax per:
  https://github.com/ifandelse/machina.js#pulling-machina-into-your-environment

### CODE REVIEW

**Comment by dominicbarnes** [comment]
Hey @aprilb, I don't really have any intention of maintaining/using these libraries anymore. I would like to transfer them either into the treetopllc organization, or just transfer them to you directly.

**Comment by aprilb** [comment]
ok cool @dominicbarnes how many of them besides the inline edit?  I can make a list and we can have them moved over --preferrably to the TreetopLLC Org.

**Comment by dominicbarnes** [comment]
Yeah, let's start with the inlineedit* ones, I'll try transferring them now and we'll see what happens.

**Comment by aprilb** [comment]
@dominicbarnes ok sweet

**Comment by dominicbarnes** [comment]
If it goes through successfully, it will break your builds. (You guys aren't working on deployments right now, are you?)

**Comment by dominicbarnes** [comment]
Hey @aprilb I am not able to transfer to @treetopllc. (don't have admin rights) I can't transfer to you until you delete your fork.

**Comment by aprilb** [comment]
@dominicbarnes I'll ping John to get these transferred --thanks for merging in the change.

**Comment by dominicbarnes** [comment]
Ok, I'll need temporary admin access to treetopllc to do so, or I can transfer them to either you or john who can then make the final transfer into treetopllc. I'm cool either way, so let me know.

**Comment by aprilb** [comment]
ok, will do.

**Comment by dominicbarnes** [comment]
fwiw, I've published v0.0.8 of this repo with this PR.

Just let me know what other libs you guys want, I'll most likely transfer all of them. There may be a handful I'll want to maintain myself, but unless that's the case I don't want to be a road-block to you.

**Pull request merged**
